"""execution engine schema

Revision ID: df824d452e42
Revises: 
Create Date: 2026-05-31 12:30:09.690613
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'df824d452e42'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_active', 'execution', ['status'], unique=False, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_index('ix_execution_org_workflow_started', 'execution', ['org_id', 'workflow_id', 'started_at'], unique=False)
    op.create_table('execution_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_event_exec_id', 'execution_event', ['execution_id', 'id'], unique=False)
    op.create_index('ix_execution_event_org_created', 'execution_event', ['org_id', 'created_at'], unique=False)
    op.create_table('node_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'node_id', name='uq_node_state_exec_node')
    )
    op.create_index('ix_node_state_claim', 'node_state', ['status', 'not_before'], unique=False)
    op.create_index('ix_node_state_lease', 'node_state', ['status', 'lease_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_node_state_lease', table_name='node_state')
    op.drop_index('ix_node_state_claim', table_name='node_state')
    op.drop_table('node_state')
    op.drop_index('ix_execution_event_org_created', table_name='execution_event')
    op.drop_index('ix_execution_event_exec_id', table_name='execution_event')
    op.drop_table('execution_event')
    op.drop_index('ix_execution_org_workflow_started', table_name='execution')
    op.drop_index('ix_execution_active', table_name='execution', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_table('execution')
    # ### end Alembic commands ###
